require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WishesController do

  # This should return the minimal set of attributes required to create a valid
  # Wish. As you add validations to Wish, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {  }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WishesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all wishes as @wishes" do
      wish = Wish.create! valid_attributes
      get :index, {}, valid_session
      assigns(:wishes).should eq([wish])
    end
  end

  describe "GET show" do
    it "assigns the requested wish as @wish" do
      wish = Wish.create! valid_attributes
      get :show, {:id => wish.to_param}, valid_session
      assigns(:wish).should eq(wish)
    end
  end

  describe "GET new" do
    it "assigns a new wish as @wish" do
      get :new, {}, valid_session
      assigns(:wish).should be_a_new(Wish)
    end
  end

  describe "GET edit" do
    it "assigns the requested wish as @wish" do
      wish = Wish.create! valid_attributes
      get :edit, {:id => wish.to_param}, valid_session
      assigns(:wish).should eq(wish)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Wish" do
        expect {
          post :create, {:wish => valid_attributes}, valid_session
        }.to change(Wish, :count).by(1)
      end

      it "assigns a newly created wish as @wish" do
        post :create, {:wish => valid_attributes}, valid_session
        assigns(:wish).should be_a(Wish)
        assigns(:wish).should be_persisted
      end

      it "redirects to the created wish" do
        post :create, {:wish => valid_attributes}, valid_session
        response.should redirect_to(Wish.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved wish as @wish" do
        # Trigger the behavior that occurs when invalid params are submitted
        Wish.any_instance.stub(:save).and_return(false)
        post :create, {:wish => {  }}, valid_session
        assigns(:wish).should be_a_new(Wish)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Wish.any_instance.stub(:save).and_return(false)
        post :create, {:wish => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested wish" do
        wish = Wish.create! valid_attributes
        # Assuming there are no other wishes in the database, this
        # specifies that the Wish created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Wish.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => wish.to_param, :wish => { "these" => "params" }}, valid_session
      end

      it "assigns the requested wish as @wish" do
        wish = Wish.create! valid_attributes
        put :update, {:id => wish.to_param, :wish => valid_attributes}, valid_session
        assigns(:wish).should eq(wish)
      end

      it "redirects to the wish" do
        wish = Wish.create! valid_attributes
        put :update, {:id => wish.to_param, :wish => valid_attributes}, valid_session
        response.should redirect_to(wish)
      end
    end

    describe "with invalid params" do
      it "assigns the wish as @wish" do
        wish = Wish.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Wish.any_instance.stub(:save).and_return(false)
        put :update, {:id => wish.to_param, :wish => {  }}, valid_session
        assigns(:wish).should eq(wish)
      end

      it "re-renders the 'edit' template" do
        wish = Wish.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Wish.any_instance.stub(:save).and_return(false)
        put :update, {:id => wish.to_param, :wish => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested wish" do
      wish = Wish.create! valid_attributes
      expect {
        delete :destroy, {:id => wish.to_param}, valid_session
      }.to change(Wish, :count).by(-1)
    end

    it "redirects to the wishes list" do
      wish = Wish.create! valid_attributes
      delete :destroy, {:id => wish.to_param}, valid_session
      response.should redirect_to(wishes_url)
    end
  end

end
